// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dto "github.com/darialissi/msa_big_tech/social/internal/app/usecases/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/darialissi/msa_big_tech/social/internal/app/models"
)

// FriendRequestRepository is an autogenerated mock type for the FriendRequestRepository type
type FriendRequestRepository struct {
	mock.Mock
}

type FriendRequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FriendRequestRepository) EXPECT() *FriendRequestRepository_Expecter {
	return &FriendRequestRepository_Expecter{mock: &_m.Mock}
}

// FetchById provides a mock function with given fields: reqId
func (_m *FriendRequestRepository) FetchById(reqId dto.FriendRequestID) (*models.FriendRequest, error) {
	ret := _m.Called(reqId)

	if len(ret) == 0 {
		panic("no return value specified for FetchById")
	}

	var r0 *models.FriendRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.FriendRequestID) (*models.FriendRequest, error)); ok {
		return rf(reqId)
	}
	if rf, ok := ret.Get(0).(func(dto.FriendRequestID) *models.FriendRequest); ok {
		r0 = rf(reqId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FriendRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.FriendRequestID) error); ok {
		r1 = rf(reqId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendRequestRepository_FetchById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchById'
type FriendRequestRepository_FetchById_Call struct {
	*mock.Call
}

// FetchById is a helper method to define mock.On call
//   - reqId dto.FriendRequestID
func (_e *FriendRequestRepository_Expecter) FetchById(reqId interface{}) *FriendRequestRepository_FetchById_Call {
	return &FriendRequestRepository_FetchById_Call{Call: _e.mock.On("FetchById", reqId)}
}

func (_c *FriendRequestRepository_FetchById_Call) Run(run func(reqId dto.FriendRequestID)) *FriendRequestRepository_FetchById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.FriendRequestID))
	})
	return _c
}

func (_c *FriendRequestRepository_FetchById_Call) Return(_a0 *models.FriendRequest, _a1 error) *FriendRequestRepository_FetchById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendRequestRepository_FetchById_Call) RunAndReturn(run func(dto.FriendRequestID) (*models.FriendRequest, error)) *FriendRequestRepository_FetchById_Call {
	_c.Call.Return(run)
	return _c
}

// FetchManyByUserId provides a mock function with given fields: userId
func (_m *FriendRequestRepository) FetchManyByUserId(userId dto.UserID) ([]*models.FriendRequest, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for FetchManyByUserId")
	}

	var r0 []*models.FriendRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.UserID) ([]*models.FriendRequest, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(dto.UserID) []*models.FriendRequest); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FriendRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.UserID) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendRequestRepository_FetchManyByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchManyByUserId'
type FriendRequestRepository_FetchManyByUserId_Call struct {
	*mock.Call
}

// FetchManyByUserId is a helper method to define mock.On call
//   - userId dto.UserID
func (_e *FriendRequestRepository_Expecter) FetchManyByUserId(userId interface{}) *FriendRequestRepository_FetchManyByUserId_Call {
	return &FriendRequestRepository_FetchManyByUserId_Call{Call: _e.mock.On("FetchManyByUserId", userId)}
}

func (_c *FriendRequestRepository_FetchManyByUserId_Call) Run(run func(userId dto.UserID)) *FriendRequestRepository_FetchManyByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.UserID))
	})
	return _c
}

func (_c *FriendRequestRepository_FetchManyByUserId_Call) Return(_a0 []*models.FriendRequest, _a1 error) *FriendRequestRepository_FetchManyByUserId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendRequestRepository_FetchManyByUserId_Call) RunAndReturn(run func(dto.UserID) ([]*models.FriendRequest, error)) *FriendRequestRepository_FetchManyByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: req
func (_m *FriendRequestRepository) Save(req *dto.SaveFriendRequest) (*models.FriendRequest, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *models.FriendRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(*dto.SaveFriendRequest) (*models.FriendRequest, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*dto.SaveFriendRequest) *models.FriendRequest); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FriendRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(*dto.SaveFriendRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendRequestRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type FriendRequestRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - req *dto.SaveFriendRequest
func (_e *FriendRequestRepository_Expecter) Save(req interface{}) *FriendRequestRepository_Save_Call {
	return &FriendRequestRepository_Save_Call{Call: _e.mock.On("Save", req)}
}

func (_c *FriendRequestRepository_Save_Call) Run(run func(req *dto.SaveFriendRequest)) *FriendRequestRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dto.SaveFriendRequest))
	})
	return _c
}

func (_c *FriendRequestRepository_Save_Call) Return(_a0 *models.FriendRequest, _a1 error) *FriendRequestRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendRequestRepository_Save_Call) RunAndReturn(run func(*dto.SaveFriendRequest) (*models.FriendRequest, error)) *FriendRequestRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: req
func (_m *FriendRequestRepository) UpdateStatus(req *dto.ChangeStatus) (*models.FriendRequest, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *models.FriendRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(*dto.ChangeStatus) (*models.FriendRequest, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*dto.ChangeStatus) *models.FriendRequest); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FriendRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(*dto.ChangeStatus) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendRequestRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type FriendRequestRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - req *dto.ChangeStatus
func (_e *FriendRequestRepository_Expecter) UpdateStatus(req interface{}) *FriendRequestRepository_UpdateStatus_Call {
	return &FriendRequestRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", req)}
}

func (_c *FriendRequestRepository_UpdateStatus_Call) Run(run func(req *dto.ChangeStatus)) *FriendRequestRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dto.ChangeStatus))
	})
	return _c
}

func (_c *FriendRequestRepository_UpdateStatus_Call) Return(_a0 *models.FriendRequest, _a1 error) *FriendRequestRepository_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendRequestRepository_UpdateStatus_Call) RunAndReturn(run func(*dto.ChangeStatus) (*models.FriendRequest, error)) *FriendRequestRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewFriendRequestRepository creates a new instance of FriendRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFriendRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FriendRequestRepository {
	mock := &FriendRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
