// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/darialissi/msa_big_tech/social/internal/app/models"
	mock "github.com/stretchr/testify/mock"
)

// FriendRepository is an autogenerated mock type for the FriendRepository type
type FriendRepository struct {
	mock.Mock
}

type FriendRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FriendRepository) EXPECT() *FriendRepository_Expecter {
	return &FriendRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, in
func (_m *FriendRepository) Delete(ctx context.Context, in *models.UserFriend) (*models.UserFriend, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *models.UserFriend
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserFriend) (*models.UserFriend, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserFriend) *models.UserFriend); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserFriend)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UserFriend) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type FriendRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - in *models.UserFriend
func (_e *FriendRepository_Expecter) Delete(ctx interface{}, in interface{}) *FriendRepository_Delete_Call {
	return &FriendRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, in)}
}

func (_c *FriendRepository_Delete_Call) Run(run func(ctx context.Context, in *models.UserFriend)) *FriendRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UserFriend))
	})
	return _c
}

func (_c *FriendRepository_Delete_Call) Return(_a0 *models.UserFriend, _a1 error) *FriendRepository_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendRepository_Delete_Call) RunAndReturn(run func(context.Context, *models.UserFriend) (*models.UserFriend, error)) *FriendRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FetchManyByUserId provides a mock function with given fields: ctx, userId
func (_m *FriendRepository) FetchManyByUserId(ctx context.Context, userId models.UserID) ([]*models.UserFriend, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for FetchManyByUserId")
	}

	var r0 []*models.UserFriend
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) ([]*models.UserFriend, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID) []*models.UserFriend); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.UserFriend)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserID) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendRepository_FetchManyByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchManyByUserId'
type FriendRepository_FetchManyByUserId_Call struct {
	*mock.Call
}

// FetchManyByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userId models.UserID
func (_e *FriendRepository_Expecter) FetchManyByUserId(ctx interface{}, userId interface{}) *FriendRepository_FetchManyByUserId_Call {
	return &FriendRepository_FetchManyByUserId_Call{Call: _e.mock.On("FetchManyByUserId", ctx, userId)}
}

func (_c *FriendRepository_FetchManyByUserId_Call) Run(run func(ctx context.Context, userId models.UserID)) *FriendRepository_FetchManyByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserID))
	})
	return _c
}

func (_c *FriendRepository_FetchManyByUserId_Call) Return(_a0 []*models.UserFriend, _a1 error) *FriendRepository_FetchManyByUserId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendRepository_FetchManyByUserId_Call) RunAndReturn(run func(context.Context, models.UserID) ([]*models.UserFriend, error)) *FriendRepository_FetchManyByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// FetchManyByUserIdCursor provides a mock function with given fields: ctx, userId, cursor
func (_m *FriendRepository) FetchManyByUserIdCursor(ctx context.Context, userId models.UserID, cursor *models.Cursor) ([]*models.UserFriend, *models.Cursor, error) {
	ret := _m.Called(ctx, userId, cursor)

	if len(ret) == 0 {
		panic("no return value specified for FetchManyByUserIdCursor")
	}

	var r0 []*models.UserFriend
	var r1 *models.Cursor
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID, *models.Cursor) ([]*models.UserFriend, *models.Cursor, error)); ok {
		return rf(ctx, userId, cursor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserID, *models.Cursor) []*models.UserFriend); ok {
		r0 = rf(ctx, userId, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.UserFriend)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserID, *models.Cursor) *models.Cursor); ok {
		r1 = rf(ctx, userId, cursor)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.Cursor)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.UserID, *models.Cursor) error); ok {
		r2 = rf(ctx, userId, cursor)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FriendRepository_FetchManyByUserIdCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchManyByUserIdCursor'
type FriendRepository_FetchManyByUserIdCursor_Call struct {
	*mock.Call
}

// FetchManyByUserIdCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - userId models.UserID
//   - cursor *models.Cursor
func (_e *FriendRepository_Expecter) FetchManyByUserIdCursor(ctx interface{}, userId interface{}, cursor interface{}) *FriendRepository_FetchManyByUserIdCursor_Call {
	return &FriendRepository_FetchManyByUserIdCursor_Call{Call: _e.mock.On("FetchManyByUserIdCursor", ctx, userId, cursor)}
}

func (_c *FriendRepository_FetchManyByUserIdCursor_Call) Run(run func(ctx context.Context, userId models.UserID, cursor *models.Cursor)) *FriendRepository_FetchManyByUserIdCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserID), args[2].(*models.Cursor))
	})
	return _c
}

func (_c *FriendRepository_FetchManyByUserIdCursor_Call) Return(_a0 []*models.UserFriend, _a1 *models.Cursor, _a2 error) *FriendRepository_FetchManyByUserIdCursor_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *FriendRepository_FetchManyByUserIdCursor_Call) RunAndReturn(run func(context.Context, models.UserID, *models.Cursor) ([]*models.UserFriend, *models.Cursor, error)) *FriendRepository_FetchManyByUserIdCursor_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, in
func (_m *FriendRepository) Save(ctx context.Context, in *models.UserFriend) (*models.UserFriend, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *models.UserFriend
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserFriend) (*models.UserFriend, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserFriend) *models.UserFriend); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserFriend)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UserFriend) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FriendRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type FriendRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - in *models.UserFriend
func (_e *FriendRepository_Expecter) Save(ctx interface{}, in interface{}) *FriendRepository_Save_Call {
	return &FriendRepository_Save_Call{Call: _e.mock.On("Save", ctx, in)}
}

func (_c *FriendRepository_Save_Call) Run(run func(ctx context.Context, in *models.UserFriend)) *FriendRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UserFriend))
	})
	return _c
}

func (_c *FriendRepository_Save_Call) Return(_a0 *models.UserFriend, _a1 error) *FriendRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FriendRepository_Save_Call) RunAndReturn(run func(context.Context, *models.UserFriend) (*models.UserFriend, error)) *FriendRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewFriendRepository creates a new instance of FriendRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFriendRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FriendRepository {
	mock := &FriendRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
