// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: api/proto/service.proto

package social

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto_service_proto protoreflect.FileDescriptor

const file_api_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/service.proto\x12)github.com.darialissi.msa_big_tech.social\x1a\x18api/proto/messages.proto\x1a\x1cgoogle/api/annotations.proto2\xe9\a\n" +
	"\rSocialService\x12\xc9\x01\n" +
	"\x11SendFriendRequest\x12C.github.com.darialissi.msa_big_tech.social.SendFriendRequestRequest\x1aD.github.com.darialissi.msa_big_tech.social.SendFriendRequestResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/friends/{user_id}/request\x12\x91\x01\n" +
	"\fListRequests\x12>.github.com.darialissi.msa_big_tech.social.ListRequestsRequest\x1a?.github.com.darialissi.msa_big_tech.social.ListRequestsResponse\"\x00\x12\xa6\x01\n" +
	"\x13AcceptFriendRequest\x12E.github.com.darialissi.msa_big_tech.social.AcceptFriendRequestRequest\x1aF.github.com.darialissi.msa_big_tech.social.AcceptFriendRequestResponse\"\x00\x12\xa9\x01\n" +
	"\x14DeclineFriendRequest\x12F.github.com.darialissi.msa_big_tech.social.DeclineFriendRequestRequest\x1aG.github.com.darialissi.msa_big_tech.social.DeclineFriendRequestResponse\"\x00\x12\x91\x01\n" +
	"\fRemoveFriend\x12>.github.com.darialissi.msa_big_tech.social.RemoveFriendRequest\x1a?.github.com.darialissi.msa_big_tech.social.RemoveFriendResponse\"\x00\x12\x8e\x01\n" +
	"\vListFriends\x12=.github.com.darialissi.msa_big_tech.social.ListFriendsRequest\x1a>.github.com.darialissi.msa_big_tech.social.ListFriendsResponse\"\x00B#Z!msa_big_tech/pkg/api/proto;socialb\x06proto3"

var file_api_proto_service_proto_goTypes = []any{
	(*SendFriendRequestRequest)(nil),     // 0: github.com.darialissi.msa_big_tech.social.SendFriendRequestRequest
	(*ListRequestsRequest)(nil),          // 1: github.com.darialissi.msa_big_tech.social.ListRequestsRequest
	(*AcceptFriendRequestRequest)(nil),   // 2: github.com.darialissi.msa_big_tech.social.AcceptFriendRequestRequest
	(*DeclineFriendRequestRequest)(nil),  // 3: github.com.darialissi.msa_big_tech.social.DeclineFriendRequestRequest
	(*RemoveFriendRequest)(nil),          // 4: github.com.darialissi.msa_big_tech.social.RemoveFriendRequest
	(*ListFriendsRequest)(nil),           // 5: github.com.darialissi.msa_big_tech.social.ListFriendsRequest
	(*SendFriendRequestResponse)(nil),    // 6: github.com.darialissi.msa_big_tech.social.SendFriendRequestResponse
	(*ListRequestsResponse)(nil),         // 7: github.com.darialissi.msa_big_tech.social.ListRequestsResponse
	(*AcceptFriendRequestResponse)(nil),  // 8: github.com.darialissi.msa_big_tech.social.AcceptFriendRequestResponse
	(*DeclineFriendRequestResponse)(nil), // 9: github.com.darialissi.msa_big_tech.social.DeclineFriendRequestResponse
	(*RemoveFriendResponse)(nil),         // 10: github.com.darialissi.msa_big_tech.social.RemoveFriendResponse
	(*ListFriendsResponse)(nil),          // 11: github.com.darialissi.msa_big_tech.social.ListFriendsResponse
}
var file_api_proto_service_proto_depIdxs = []int32{
	0,  // 0: github.com.darialissi.msa_big_tech.social.SocialService.SendFriendRequest:input_type -> github.com.darialissi.msa_big_tech.social.SendFriendRequestRequest
	1,  // 1: github.com.darialissi.msa_big_tech.social.SocialService.ListRequests:input_type -> github.com.darialissi.msa_big_tech.social.ListRequestsRequest
	2,  // 2: github.com.darialissi.msa_big_tech.social.SocialService.AcceptFriendRequest:input_type -> github.com.darialissi.msa_big_tech.social.AcceptFriendRequestRequest
	3,  // 3: github.com.darialissi.msa_big_tech.social.SocialService.DeclineFriendRequest:input_type -> github.com.darialissi.msa_big_tech.social.DeclineFriendRequestRequest
	4,  // 4: github.com.darialissi.msa_big_tech.social.SocialService.RemoveFriend:input_type -> github.com.darialissi.msa_big_tech.social.RemoveFriendRequest
	5,  // 5: github.com.darialissi.msa_big_tech.social.SocialService.ListFriends:input_type -> github.com.darialissi.msa_big_tech.social.ListFriendsRequest
	6,  // 6: github.com.darialissi.msa_big_tech.social.SocialService.SendFriendRequest:output_type -> github.com.darialissi.msa_big_tech.social.SendFriendRequestResponse
	7,  // 7: github.com.darialissi.msa_big_tech.social.SocialService.ListRequests:output_type -> github.com.darialissi.msa_big_tech.social.ListRequestsResponse
	8,  // 8: github.com.darialissi.msa_big_tech.social.SocialService.AcceptFriendRequest:output_type -> github.com.darialissi.msa_big_tech.social.AcceptFriendRequestResponse
	9,  // 9: github.com.darialissi.msa_big_tech.social.SocialService.DeclineFriendRequest:output_type -> github.com.darialissi.msa_big_tech.social.DeclineFriendRequestResponse
	10, // 10: github.com.darialissi.msa_big_tech.social.SocialService.RemoveFriend:output_type -> github.com.darialissi.msa_big_tech.social.RemoveFriendResponse
	11, // 11: github.com.darialissi.msa_big_tech.social.SocialService.ListFriends:output_type -> github.com.darialissi.msa_big_tech.social.ListFriendsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_service_proto_init() }
func file_api_proto_service_proto_init() {
	if File_api_proto_service_proto != nil {
		return
	}
	file_api_proto_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_service_proto_rawDesc), len(file_api_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_service_proto_goTypes,
		DependencyIndexes: file_api_proto_service_proto_depIdxs,
	}.Build()
	File_api_proto_service_proto = out.File
	file_api_proto_service_proto_goTypes = nil
	file_api_proto_service_proto_depIdxs = nil
}
