// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: api/proto/service.proto

package auth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto_service_proto protoreflect.FileDescriptor

const file_api_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/service.proto\x12'github.com.darialissi.msa_big_tech.auth\x1a\x18api/proto/messages.proto\x1a\x1cgoogle/api/annotations.proto2\xbf\x03\n" +
	"\vAuthService\x12\x9c\x01\n" +
	"\bRegister\x128.github.com.darialissi.msa_big_tech.auth.RegisterRequest\x1a9.github.com.darialissi.msa_big_tech.auth.RegisterResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/register\x12\x90\x01\n" +
	"\x05Login\x125.github.com.darialissi.msa_big_tech.auth.LoginRequest\x1a6.github.com.darialissi.msa_big_tech.auth.LoginResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/login\x12~\n" +
	"\aRefresh\x127.github.com.darialissi.msa_big_tech.auth.RefreshRequest\x1a8.github.com.darialissi.msa_big_tech.auth.RefreshResponse\"\x00B!Z\x1fmsa_big_tech/pkg/api/proto;authb\x06proto3"

var file_api_proto_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: github.com.darialissi.msa_big_tech.auth.RegisterRequest
	(*LoginRequest)(nil),     // 1: github.com.darialissi.msa_big_tech.auth.LoginRequest
	(*RefreshRequest)(nil),   // 2: github.com.darialissi.msa_big_tech.auth.RefreshRequest
	(*RegisterResponse)(nil), // 3: github.com.darialissi.msa_big_tech.auth.RegisterResponse
	(*LoginResponse)(nil),    // 4: github.com.darialissi.msa_big_tech.auth.LoginResponse
	(*RefreshResponse)(nil),  // 5: github.com.darialissi.msa_big_tech.auth.RefreshResponse
}
var file_api_proto_service_proto_depIdxs = []int32{
	0, // 0: github.com.darialissi.msa_big_tech.auth.AuthService.Register:input_type -> github.com.darialissi.msa_big_tech.auth.RegisterRequest
	1, // 1: github.com.darialissi.msa_big_tech.auth.AuthService.Login:input_type -> github.com.darialissi.msa_big_tech.auth.LoginRequest
	2, // 2: github.com.darialissi.msa_big_tech.auth.AuthService.Refresh:input_type -> github.com.darialissi.msa_big_tech.auth.RefreshRequest
	3, // 3: github.com.darialissi.msa_big_tech.auth.AuthService.Register:output_type -> github.com.darialissi.msa_big_tech.auth.RegisterResponse
	4, // 4: github.com.darialissi.msa_big_tech.auth.AuthService.Login:output_type -> github.com.darialissi.msa_big_tech.auth.LoginResponse
	5, // 5: github.com.darialissi.msa_big_tech.auth.AuthService.Refresh:output_type -> github.com.darialissi.msa_big_tech.auth.RefreshResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_service_proto_init() }
func file_api_proto_service_proto_init() {
	if File_api_proto_service_proto != nil {
		return
	}
	file_api_proto_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_service_proto_rawDesc), len(file_api_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_service_proto_goTypes,
		DependencyIndexes: file_api_proto_service_proto_depIdxs,
	}.Build()
	File_api_proto_service_proto = out.File
	file_api_proto_service_proto_goTypes = nil
	file_api_proto_service_proto_depIdxs = nil
}
