// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Создание личного чата
type CreateDirectChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId uint64                 `protobuf:"varint,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatRequest) Reset() {
	*x = CreateDirectChatRequest{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatRequest) ProtoMessage() {}

func (x *CreateDirectChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDirectChatRequest) GetParticipantId() uint64 {
	if x != nil {
		return x.ParticipantId
	}
	return 0
}

type CreateDirectChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        uint64                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatResponse) Reset() {
	*x = CreateDirectChatResponse{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatResponse) ProtoMessage() {}

func (x *CreateDirectChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDirectChatResponse) GetChatId() uint64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

// Получение информации о чате
type GetChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        uint64                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetChatRequest) GetChatId() uint64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type GetChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatResponse) Reset() {
	*x = GetChatResponse{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatResponse) ProtoMessage() {}

func (x *GetChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatResponse.ProtoReflect.Descriptor instead.
func (*GetChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

// Получение списка чатов пользователя
type ListUserChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsRequest) Reset() {
	*x = ListUserChatsRequest{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsRequest) ProtoMessage() {}

func (x *ListUserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsRequest.ProtoReflect.Descriptor instead.
func (*ListUserChatsRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserChatsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListUserChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsResponse) Reset() {
	*x = ListUserChatsResponse{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsResponse) ProtoMessage() {}

func (x *ListUserChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsResponse.ProtoReflect.Descriptor instead.
func (*ListUserChatsResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

// Получение списка участников чата
type ListChatMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        uint64                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMembersRequest) Reset() {
	*x = ListChatMembersRequest{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMembersRequest) ProtoMessage() {}

func (x *ListChatMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMembersRequest.ProtoReflect.Descriptor instead.
func (*ListChatMembersRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ListChatMembersRequest) GetChatId() uint64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type ListChatMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []uint64               `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMembersResponse) Reset() {
	*x = ListChatMembersResponse{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMembersResponse) ProtoMessage() {}

func (x *ListChatMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMembersResponse.ProtoReflect.Descriptor instead.
func (*ListChatMembersResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ListChatMembersResponse) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// Отправление сообщения
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        uint64                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetChatId() uint64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// Получение истории сообщений чата
type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        uint64                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *ListMessagesRequest) GetChatId() uint64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ListMessagesRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Серверный стрим новых сообщений
type StreamMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        uint64                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesRequest) Reset() {
	*x = StreamMessagesRequest{}
	mi := &file_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesRequest) ProtoMessage() {}

func (x *StreamMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *StreamMessagesRequest) GetChatId() uint64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type StreamMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *Message               `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesResponse) Reset() {
	*x = StreamMessagesResponse{}
	mi := &file_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesResponse) ProtoMessage() {}

func (x *StreamMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesResponse.ProtoReflect.Descriptor instead.
func (*StreamMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{13}
}

func (x *StreamMessagesResponse) GetStream() *Message {
	if x != nil {
		return x.Stream
	}
	return nil
}

// Объекты
type Chat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChatId         uint64                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatorId      uint64                 `protobuf:"varint,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParticipantIds []uint64               `protobuf:"varint,4,rep,packed,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{14}
}

func (x *Chat) GetChatId() uint64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *Chat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chat) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *Chat) GetParticipantIds() []uint64 {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     uint64                 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	FromUserId    uint64                 `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToChatId      uint64                 `protobuf:"varint,4,opt,name=to_chat_id,json=toChatId,proto3" json:"to_chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{15}
}

func (x *Message) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *Message) GetToChatId() uint64 {
	if x != nil {
		return x.ToChatId
	}
	return 0
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12'github.com.darialissi.msa_big_tech.chat\"@\n" +
	"\x17CreateDirectChatRequest\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\x04R\rparticipantId\"3\n" +
	"\x18CreateDirectChatResponse\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x04R\x06chatId\")\n" +
	"\x0eGetChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x04R\x06chatId\"T\n" +
	"\x0fGetChatResponse\x12A\n" +
	"\x04chat\x18\x01 \x01(\v2-.github.com.darialissi.msa_big_tech.chat.ChatR\x04chat\"/\n" +
	"\x14ListUserChatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\\\n" +
	"\x15ListUserChatsResponse\x12C\n" +
	"\x05chats\x18\x01 \x03(\v2-.github.com.darialissi.msa_big_tech.chat.ChatR\x05chats\"1\n" +
	"\x16ListChatMembersRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x04R\x06chatId\"4\n" +
	"\x17ListChatMembersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x04R\auserIds\"A\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x04R\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"a\n" +
	"\x13SendMessageResponse\x12J\n" +
	"\amessage\x18\x01 \x01(\v20.github.com.darialissi.msa_big_tech.chat.MessageR\amessage\"D\n" +
	"\x13ListMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x04R\x06chatId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"d\n" +
	"\x14ListMessagesResponse\x12L\n" +
	"\bmessages\x18\x01 \x03(\v20.github.com.darialissi.msa_big_tech.chat.MessageR\bmessages\"0\n" +
	"\x15StreamMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x04R\x06chatId\"b\n" +
	"\x16StreamMessagesResponse\x12H\n" +
	"\x06stream\x18\x01 \x01(\v20.github.com.darialissi.msa_big_tech.chat.MessageR\x06stream\"{\n" +
	"\x04Chat\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x04R\x06chatId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\x04R\tcreatorId\x12'\n" +
	"\x0fparticipant_ids\x18\x04 \x03(\x04R\x0eparticipantIds\"|\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x04R\tmessageId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x04R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_chat_id\x18\x04 \x01(\x04R\btoChatIdB\xa4\x02\n" +
	"+com.github.com.darialissi.msa_big_tech.chatB\tChatProtoP\x01Z0github.com/darialissi/msa_big_tech/chat/pkg;chat\xa2\x02\x05GCDMC\xaa\x02%Github.Com.Darialissi.MsaBigTech.Chat\xca\x02%Github\\Com\\Darialissi\\MsaBigTech\\Chat\xe2\x021Github\\Com\\Darialissi\\MsaBigTech\\Chat\\GPBMetadata\xea\x02)Github::Com::Darialissi::MsaBigTech::Chatb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_chat_proto_goTypes = []any{
	(*CreateDirectChatRequest)(nil),  // 0: github.com.darialissi.msa_big_tech.chat.CreateDirectChatRequest
	(*CreateDirectChatResponse)(nil), // 1: github.com.darialissi.msa_big_tech.chat.CreateDirectChatResponse
	(*GetChatRequest)(nil),           // 2: github.com.darialissi.msa_big_tech.chat.GetChatRequest
	(*GetChatResponse)(nil),          // 3: github.com.darialissi.msa_big_tech.chat.GetChatResponse
	(*ListUserChatsRequest)(nil),     // 4: github.com.darialissi.msa_big_tech.chat.ListUserChatsRequest
	(*ListUserChatsResponse)(nil),    // 5: github.com.darialissi.msa_big_tech.chat.ListUserChatsResponse
	(*ListChatMembersRequest)(nil),   // 6: github.com.darialissi.msa_big_tech.chat.ListChatMembersRequest
	(*ListChatMembersResponse)(nil),  // 7: github.com.darialissi.msa_big_tech.chat.ListChatMembersResponse
	(*SendMessageRequest)(nil),       // 8: github.com.darialissi.msa_big_tech.chat.SendMessageRequest
	(*SendMessageResponse)(nil),      // 9: github.com.darialissi.msa_big_tech.chat.SendMessageResponse
	(*ListMessagesRequest)(nil),      // 10: github.com.darialissi.msa_big_tech.chat.ListMessagesRequest
	(*ListMessagesResponse)(nil),     // 11: github.com.darialissi.msa_big_tech.chat.ListMessagesResponse
	(*StreamMessagesRequest)(nil),    // 12: github.com.darialissi.msa_big_tech.chat.StreamMessagesRequest
	(*StreamMessagesResponse)(nil),   // 13: github.com.darialissi.msa_big_tech.chat.StreamMessagesResponse
	(*Chat)(nil),                     // 14: github.com.darialissi.msa_big_tech.chat.Chat
	(*Message)(nil),                  // 15: github.com.darialissi.msa_big_tech.chat.Message
}
var file_chat_proto_depIdxs = []int32{
	14, // 0: github.com.darialissi.msa_big_tech.chat.GetChatResponse.chat:type_name -> github.com.darialissi.msa_big_tech.chat.Chat
	14, // 1: github.com.darialissi.msa_big_tech.chat.ListUserChatsResponse.chats:type_name -> github.com.darialissi.msa_big_tech.chat.Chat
	15, // 2: github.com.darialissi.msa_big_tech.chat.SendMessageResponse.message:type_name -> github.com.darialissi.msa_big_tech.chat.Message
	15, // 3: github.com.darialissi.msa_big_tech.chat.ListMessagesResponse.messages:type_name -> github.com.darialissi.msa_big_tech.chat.Message
	15, // 4: github.com.darialissi.msa_big_tech.chat.StreamMessagesResponse.stream:type_name -> github.com.darialissi.msa_big_tech.chat.Message
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
