// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: service.proto

package chat

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12'github.com.darialissi.msa_big_tech.chat\x1a\x0emessages.proto\x1a\x1cgoogle/api/annotations.proto2\xb2\b\n" +
	"\vChatService\x12\x99\x01\n" +
	"\x10CreateDirectChat\x12@.github.com.darialissi.msa_big_tech.chat.CreateDirectChatRequest\x1aA.github.com.darialissi.msa_big_tech.chat.CreateDirectChatResponse\"\x00\x12~\n" +
	"\aGetChat\x127.github.com.darialissi.msa_big_tech.chat.GetChatRequest\x1a8.github.com.darialissi.msa_big_tech.chat.GetChatResponse\"\x00\x12\x90\x01\n" +
	"\rListUserChats\x12=.github.com.darialissi.msa_big_tech.chat.ListUserChatsRequest\x1a>.github.com.darialissi.msa_big_tech.chat.ListUserChatsResponse\"\x00\x12\x96\x01\n" +
	"\x0fListChatMembers\x12?.github.com.darialissi.msa_big_tech.chat.ListChatMembersRequest\x1a@.github.com.darialissi.msa_big_tech.chat.ListChatMembersResponse\"\x00\x12\xb4\x01\n" +
	"\vSendMessage\x12;.github.com.darialissi.msa_big_tech.chat.SendMessageRequest\x1a<.github.com.darialissi.msa_big_tech.chat.SendMessageResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/chats/{chat_id}/message\x12\x8d\x01\n" +
	"\fListMessages\x12<.github.com.darialissi.msa_big_tech.chat.ListMessagesRequest\x1a=.github.com.darialissi.msa_big_tech.chat.ListMessagesResponse\"\x00\x12\x93\x01\n" +
	"\x0eStreamMessages\x12>.github.com.darialissi.msa_big_tech.chat.StreamMessagesRequest\x1a?.github.com.darialissi.msa_big_tech.chat.StreamMessagesResponse\"\x00B\x91\x02\n" +
	"+com.github.com.darialissi.msa_big_tech.chatB\fServiceProtoP\x01Z\x1amsa_big_tech/chat/pkg;chat\xa2\x02\x05GCDMC\xaa\x02%Github.Com.Darialissi.MsaBigTech.Chat\xca\x02%Github\\Com\\Darialissi\\MsaBigTech\\Chat\xe2\x021Github\\Com\\Darialissi\\MsaBigTech\\Chat\\GPBMetadata\xea\x02)Github::Com::Darialissi::MsaBigTech::Chatb\x06proto3"

var file_service_proto_goTypes = []any{
	(*CreateDirectChatRequest)(nil),  // 0: github.com.darialissi.msa_big_tech.chat.CreateDirectChatRequest
	(*GetChatRequest)(nil),           // 1: github.com.darialissi.msa_big_tech.chat.GetChatRequest
	(*ListUserChatsRequest)(nil),     // 2: github.com.darialissi.msa_big_tech.chat.ListUserChatsRequest
	(*ListChatMembersRequest)(nil),   // 3: github.com.darialissi.msa_big_tech.chat.ListChatMembersRequest
	(*SendMessageRequest)(nil),       // 4: github.com.darialissi.msa_big_tech.chat.SendMessageRequest
	(*ListMessagesRequest)(nil),      // 5: github.com.darialissi.msa_big_tech.chat.ListMessagesRequest
	(*StreamMessagesRequest)(nil),    // 6: github.com.darialissi.msa_big_tech.chat.StreamMessagesRequest
	(*CreateDirectChatResponse)(nil), // 7: github.com.darialissi.msa_big_tech.chat.CreateDirectChatResponse
	(*GetChatResponse)(nil),          // 8: github.com.darialissi.msa_big_tech.chat.GetChatResponse
	(*ListUserChatsResponse)(nil),    // 9: github.com.darialissi.msa_big_tech.chat.ListUserChatsResponse
	(*ListChatMembersResponse)(nil),  // 10: github.com.darialissi.msa_big_tech.chat.ListChatMembersResponse
	(*SendMessageResponse)(nil),      // 11: github.com.darialissi.msa_big_tech.chat.SendMessageResponse
	(*ListMessagesResponse)(nil),     // 12: github.com.darialissi.msa_big_tech.chat.ListMessagesResponse
	(*StreamMessagesResponse)(nil),   // 13: github.com.darialissi.msa_big_tech.chat.StreamMessagesResponse
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: github.com.darialissi.msa_big_tech.chat.ChatService.CreateDirectChat:input_type -> github.com.darialissi.msa_big_tech.chat.CreateDirectChatRequest
	1,  // 1: github.com.darialissi.msa_big_tech.chat.ChatService.GetChat:input_type -> github.com.darialissi.msa_big_tech.chat.GetChatRequest
	2,  // 2: github.com.darialissi.msa_big_tech.chat.ChatService.ListUserChats:input_type -> github.com.darialissi.msa_big_tech.chat.ListUserChatsRequest
	3,  // 3: github.com.darialissi.msa_big_tech.chat.ChatService.ListChatMembers:input_type -> github.com.darialissi.msa_big_tech.chat.ListChatMembersRequest
	4,  // 4: github.com.darialissi.msa_big_tech.chat.ChatService.SendMessage:input_type -> github.com.darialissi.msa_big_tech.chat.SendMessageRequest
	5,  // 5: github.com.darialissi.msa_big_tech.chat.ChatService.ListMessages:input_type -> github.com.darialissi.msa_big_tech.chat.ListMessagesRequest
	6,  // 6: github.com.darialissi.msa_big_tech.chat.ChatService.StreamMessages:input_type -> github.com.darialissi.msa_big_tech.chat.StreamMessagesRequest
	7,  // 7: github.com.darialissi.msa_big_tech.chat.ChatService.CreateDirectChat:output_type -> github.com.darialissi.msa_big_tech.chat.CreateDirectChatResponse
	8,  // 8: github.com.darialissi.msa_big_tech.chat.ChatService.GetChat:output_type -> github.com.darialissi.msa_big_tech.chat.GetChatResponse
	9,  // 9: github.com.darialissi.msa_big_tech.chat.ChatService.ListUserChats:output_type -> github.com.darialissi.msa_big_tech.chat.ListUserChatsResponse
	10, // 10: github.com.darialissi.msa_big_tech.chat.ChatService.ListChatMembers:output_type -> github.com.darialissi.msa_big_tech.chat.ListChatMembersResponse
	11, // 11: github.com.darialissi.msa_big_tech.chat.ChatService.SendMessage:output_type -> github.com.darialissi.msa_big_tech.chat.SendMessageResponse
	12, // 12: github.com.darialissi.msa_big_tech.chat.ChatService.ListMessages:output_type -> github.com.darialissi.msa_big_tech.chat.ListMessagesResponse
	13, // 13: github.com.darialissi.msa_big_tech.chat.ChatService.StreamMessages:output_type -> github.com.darialissi.msa_big_tech.chat.StreamMessagesResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
