// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/darialissi/msa_big_tech/social/internal/app/models"
	mock "github.com/stretchr/testify/mock"
)

// OutboxRepository is an autogenerated mock type for the OutboxRepository type
type OutboxRepository struct {
	mock.Mock
}

type OutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OutboxRepository) EXPECT() *OutboxRepository_Expecter {
	return &OutboxRepository_Expecter{mock: &_m.Mock}
}

// SaveFriendRequestCreated provides a mock function with given fields: ctx, req
func (_m *OutboxRepository) SaveFriendRequestCreated(ctx context.Context, req *models.FriendRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SaveFriendRequestCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FriendRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OutboxRepository_SaveFriendRequestCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFriendRequestCreated'
type OutboxRepository_SaveFriendRequestCreated_Call struct {
	*mock.Call
}

// SaveFriendRequestCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.FriendRequest
func (_e *OutboxRepository_Expecter) SaveFriendRequestCreated(ctx interface{}, req interface{}) *OutboxRepository_SaveFriendRequestCreated_Call {
	return &OutboxRepository_SaveFriendRequestCreated_Call{Call: _e.mock.On("SaveFriendRequestCreated", ctx, req)}
}

func (_c *OutboxRepository_SaveFriendRequestCreated_Call) Run(run func(ctx context.Context, req *models.FriendRequest)) *OutboxRepository_SaveFriendRequestCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FriendRequest))
	})
	return _c
}

func (_c *OutboxRepository_SaveFriendRequestCreated_Call) Return(_a0 error) *OutboxRepository_SaveFriendRequestCreated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OutboxRepository_SaveFriendRequestCreated_Call) RunAndReturn(run func(context.Context, *models.FriendRequest) error) *OutboxRepository_SaveFriendRequestCreated_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFriendRequestUpdated provides a mock function with given fields: ctx, req
func (_m *OutboxRepository) SaveFriendRequestUpdated(ctx context.Context, req *models.FriendRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SaveFriendRequestUpdated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FriendRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OutboxRepository_SaveFriendRequestUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFriendRequestUpdated'
type OutboxRepository_SaveFriendRequestUpdated_Call struct {
	*mock.Call
}

// SaveFriendRequestUpdated is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.FriendRequest
func (_e *OutboxRepository_Expecter) SaveFriendRequestUpdated(ctx interface{}, req interface{}) *OutboxRepository_SaveFriendRequestUpdated_Call {
	return &OutboxRepository_SaveFriendRequestUpdated_Call{Call: _e.mock.On("SaveFriendRequestUpdated", ctx, req)}
}

func (_c *OutboxRepository_SaveFriendRequestUpdated_Call) Run(run func(ctx context.Context, req *models.FriendRequest)) *OutboxRepository_SaveFriendRequestUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FriendRequest))
	})
	return _c
}

func (_c *OutboxRepository_SaveFriendRequestUpdated_Call) Return(_a0 error) *OutboxRepository_SaveFriendRequestUpdated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OutboxRepository_SaveFriendRequestUpdated_Call) RunAndReturn(run func(context.Context, *models.FriendRequest) error) *OutboxRepository_SaveFriendRequestUpdated_Call {
	_c.Call.Return(run)
	return _c
}

// NewOutboxRepository creates a new instance of OutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboxRepository {
	mock := &OutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
