// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: social_service.proto

package social

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_social_service_proto protoreflect.FileDescriptor

const file_social_service_proto_rawDesc = "" +
	"\n" +
	"\x14social_service.proto\x12)github.com.darialissi.msa_big_tech.social\x1a\fsocial.proto\x1a\x1cgoogle/api/annotations.proto2\xf5\a\n" +
	"\rSocialService\x12\xc3\x01\n" +
	"\x11SendFriendRequest\x12C.github.com.darialissi.msa_big_tech.social.SendFriendRequestRequest\x1aD.github.com.darialissi.msa_big_tech.social.SendFriendRequestResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/friends/requests\x12\xa3\x01\n" +
	"\x12ListFriendRequests\x12D.github.com.darialissi.msa_big_tech.social.ListFriendRequestsRequest\x1aE.github.com.darialissi.msa_big_tech.social.ListFriendRequestsResponse\"\x00\x12\xa6\x01\n" +
	"\x13AcceptFriendRequest\x12E.github.com.darialissi.msa_big_tech.social.AcceptFriendRequestRequest\x1aF.github.com.darialissi.msa_big_tech.social.AcceptFriendRequestResponse\"\x00\x12\xa9\x01\n" +
	"\x14DeclineFriendRequest\x12F.github.com.darialissi.msa_big_tech.social.DeclineFriendRequestRequest\x1aG.github.com.darialissi.msa_big_tech.social.DeclineFriendRequestResponse\"\x00\x12\x91\x01\n" +
	"\fRemoveFriend\x12>.github.com.darialissi.msa_big_tech.social.RemoveFriendRequest\x1a?.github.com.darialissi.msa_big_tech.social.RemoveFriendResponse\"\x00\x12\x8e\x01\n" +
	"\vListFriends\x12=.github.com.darialissi.msa_big_tech.social.ListFriendsRequest\x1a>.github.com.darialissi.msa_big_tech.social.ListFriendsResponse\"\x00B\xbb\x02\n" +
	"-com.github.com.darialissi.msa_big_tech.socialB\x12SocialServiceProtoP\x01Z4github.com/darialissi/msa_big_tech/social/pkg;social\xa2\x02\x05GCDMS\xaa\x02'Github.Com.Darialissi.MsaBigTech.Social\xca\x02'Github\\Com\\Darialissi\\MsaBigTech\\Social\xe2\x023Github\\Com\\Darialissi\\MsaBigTech\\Social\\GPBMetadata\xea\x02+Github::Com::Darialissi::MsaBigTech::Socialb\x06proto3"

var file_social_service_proto_goTypes = []any{
	(*SendFriendRequestRequest)(nil),     // 0: github.com.darialissi.msa_big_tech.social.SendFriendRequestRequest
	(*ListFriendRequestsRequest)(nil),    // 1: github.com.darialissi.msa_big_tech.social.ListFriendRequestsRequest
	(*AcceptFriendRequestRequest)(nil),   // 2: github.com.darialissi.msa_big_tech.social.AcceptFriendRequestRequest
	(*DeclineFriendRequestRequest)(nil),  // 3: github.com.darialissi.msa_big_tech.social.DeclineFriendRequestRequest
	(*RemoveFriendRequest)(nil),          // 4: github.com.darialissi.msa_big_tech.social.RemoveFriendRequest
	(*ListFriendsRequest)(nil),           // 5: github.com.darialissi.msa_big_tech.social.ListFriendsRequest
	(*SendFriendRequestResponse)(nil),    // 6: github.com.darialissi.msa_big_tech.social.SendFriendRequestResponse
	(*ListFriendRequestsResponse)(nil),   // 7: github.com.darialissi.msa_big_tech.social.ListFriendRequestsResponse
	(*AcceptFriendRequestResponse)(nil),  // 8: github.com.darialissi.msa_big_tech.social.AcceptFriendRequestResponse
	(*DeclineFriendRequestResponse)(nil), // 9: github.com.darialissi.msa_big_tech.social.DeclineFriendRequestResponse
	(*RemoveFriendResponse)(nil),         // 10: github.com.darialissi.msa_big_tech.social.RemoveFriendResponse
	(*ListFriendsResponse)(nil),          // 11: github.com.darialissi.msa_big_tech.social.ListFriendsResponse
}
var file_social_service_proto_depIdxs = []int32{
	0,  // 0: github.com.darialissi.msa_big_tech.social.SocialService.SendFriendRequest:input_type -> github.com.darialissi.msa_big_tech.social.SendFriendRequestRequest
	1,  // 1: github.com.darialissi.msa_big_tech.social.SocialService.ListFriendRequests:input_type -> github.com.darialissi.msa_big_tech.social.ListFriendRequestsRequest
	2,  // 2: github.com.darialissi.msa_big_tech.social.SocialService.AcceptFriendRequest:input_type -> github.com.darialissi.msa_big_tech.social.AcceptFriendRequestRequest
	3,  // 3: github.com.darialissi.msa_big_tech.social.SocialService.DeclineFriendRequest:input_type -> github.com.darialissi.msa_big_tech.social.DeclineFriendRequestRequest
	4,  // 4: github.com.darialissi.msa_big_tech.social.SocialService.RemoveFriend:input_type -> github.com.darialissi.msa_big_tech.social.RemoveFriendRequest
	5,  // 5: github.com.darialissi.msa_big_tech.social.SocialService.ListFriends:input_type -> github.com.darialissi.msa_big_tech.social.ListFriendsRequest
	6,  // 6: github.com.darialissi.msa_big_tech.social.SocialService.SendFriendRequest:output_type -> github.com.darialissi.msa_big_tech.social.SendFriendRequestResponse
	7,  // 7: github.com.darialissi.msa_big_tech.social.SocialService.ListFriendRequests:output_type -> github.com.darialissi.msa_big_tech.social.ListFriendRequestsResponse
	8,  // 8: github.com.darialissi.msa_big_tech.social.SocialService.AcceptFriendRequest:output_type -> github.com.darialissi.msa_big_tech.social.AcceptFriendRequestResponse
	9,  // 9: github.com.darialissi.msa_big_tech.social.SocialService.DeclineFriendRequest:output_type -> github.com.darialissi.msa_big_tech.social.DeclineFriendRequestResponse
	10, // 10: github.com.darialissi.msa_big_tech.social.SocialService.RemoveFriend:output_type -> github.com.darialissi.msa_big_tech.social.RemoveFriendResponse
	11, // 11: github.com.darialissi.msa_big_tech.social.SocialService.ListFriends:output_type -> github.com.darialissi.msa_big_tech.social.ListFriendsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_social_service_proto_init() }
func file_social_service_proto_init() {
	if File_social_service_proto != nil {
		return
	}
	file_social_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_service_proto_rawDesc), len(file_social_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_social_service_proto_goTypes,
		DependencyIndexes: file_social_service_proto_depIdxs,
	}.Build()
	File_social_service_proto = out.File
	file_social_service_proto_goTypes = nil
	file_social_service_proto_depIdxs = nil
}
