// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: api/proto/service.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto_service_proto protoreflect.FileDescriptor

const file_api_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/service.proto\x12(github.com.darialissi.msa_big_tech.users\x1a\x18api/proto/messages.proto2\x98\x06\n" +
	"\fUsersService\x12\x92\x01\n" +
	"\rCreateProfile\x12>.github.com.darialissi.msa_big_tech.users.CreateProfileRequest\x1a?.github.com.darialissi.msa_big_tech.users.CreateProfileResponse\"\x00\x12\x92\x01\n" +
	"\rUpdateProfile\x12>.github.com.darialissi.msa_big_tech.users.UpdateProfileRequest\x1a?.github.com.darialissi.msa_big_tech.users.UpdateProfileResponse\"\x00\x12\x95\x01\n" +
	"\x0eGetProfileByID\x12?.github.com.darialissi.msa_big_tech.users.GetProfileByIDRequest\x1a@.github.com.darialissi.msa_big_tech.users.GetProfileByIDResponse\"\x00\x12\xa7\x01\n" +
	"\x14GetProfileByNickname\x12E.github.com.darialissi.msa_big_tech.users.GetProfileByNicknameRequest\x1aF.github.com.darialissi.msa_big_tech.users.GetProfileByNicknameResponse\"\x00\x12\x9b\x01\n" +
	"\x10SearchByNickname\x12A.github.com.darialissi.msa_big_tech.users.SearchByNicknameRequest\x1aB.github.com.darialissi.msa_big_tech.users.SearchByNicknameResponse\"\x00B\"Z msa_big_tech/pkg/api/proto;usersb\x06proto3"

var file_api_proto_service_proto_goTypes = []any{
	(*CreateProfileRequest)(nil),         // 0: github.com.darialissi.msa_big_tech.users.CreateProfileRequest
	(*UpdateProfileRequest)(nil),         // 1: github.com.darialissi.msa_big_tech.users.UpdateProfileRequest
	(*GetProfileByIDRequest)(nil),        // 2: github.com.darialissi.msa_big_tech.users.GetProfileByIDRequest
	(*GetProfileByNicknameRequest)(nil),  // 3: github.com.darialissi.msa_big_tech.users.GetProfileByNicknameRequest
	(*SearchByNicknameRequest)(nil),      // 4: github.com.darialissi.msa_big_tech.users.SearchByNicknameRequest
	(*CreateProfileResponse)(nil),        // 5: github.com.darialissi.msa_big_tech.users.CreateProfileResponse
	(*UpdateProfileResponse)(nil),        // 6: github.com.darialissi.msa_big_tech.users.UpdateProfileResponse
	(*GetProfileByIDResponse)(nil),       // 7: github.com.darialissi.msa_big_tech.users.GetProfileByIDResponse
	(*GetProfileByNicknameResponse)(nil), // 8: github.com.darialissi.msa_big_tech.users.GetProfileByNicknameResponse
	(*SearchByNicknameResponse)(nil),     // 9: github.com.darialissi.msa_big_tech.users.SearchByNicknameResponse
}
var file_api_proto_service_proto_depIdxs = []int32{
	0, // 0: github.com.darialissi.msa_big_tech.users.UsersService.CreateProfile:input_type -> github.com.darialissi.msa_big_tech.users.CreateProfileRequest
	1, // 1: github.com.darialissi.msa_big_tech.users.UsersService.UpdateProfile:input_type -> github.com.darialissi.msa_big_tech.users.UpdateProfileRequest
	2, // 2: github.com.darialissi.msa_big_tech.users.UsersService.GetProfileByID:input_type -> github.com.darialissi.msa_big_tech.users.GetProfileByIDRequest
	3, // 3: github.com.darialissi.msa_big_tech.users.UsersService.GetProfileByNickname:input_type -> github.com.darialissi.msa_big_tech.users.GetProfileByNicknameRequest
	4, // 4: github.com.darialissi.msa_big_tech.users.UsersService.SearchByNickname:input_type -> github.com.darialissi.msa_big_tech.users.SearchByNicknameRequest
	5, // 5: github.com.darialissi.msa_big_tech.users.UsersService.CreateProfile:output_type -> github.com.darialissi.msa_big_tech.users.CreateProfileResponse
	6, // 6: github.com.darialissi.msa_big_tech.users.UsersService.UpdateProfile:output_type -> github.com.darialissi.msa_big_tech.users.UpdateProfileResponse
	7, // 7: github.com.darialissi.msa_big_tech.users.UsersService.GetProfileByID:output_type -> github.com.darialissi.msa_big_tech.users.GetProfileByIDResponse
	8, // 8: github.com.darialissi.msa_big_tech.users.UsersService.GetProfileByNickname:output_type -> github.com.darialissi.msa_big_tech.users.GetProfileByNicknameResponse
	9, // 9: github.com.darialissi.msa_big_tech.users.UsersService.SearchByNickname:output_type -> github.com.darialissi.msa_big_tech.users.SearchByNicknameResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_service_proto_init() }
func file_api_proto_service_proto_init() {
	if File_api_proto_service_proto != nil {
		return
	}
	file_api_proto_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_service_proto_rawDesc), len(file_api_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_service_proto_goTypes,
		DependencyIndexes: file_api_proto_service_proto_depIdxs,
	}.Build()
	File_api_proto_service_proto = out.File
	file_api_proto_service_proto_goTypes = nil
	file_api_proto_service_proto_depIdxs = nil
}
